"""add core models (fixed)

Revision ID: a4b82e4bfa93
Revises: 45547b638395
Create Date: 2025-08-19 18:05:18.591003

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a4b82e4bfa93"
down_revision: Union[str, Sequence[str], None] = "45547b638395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
