services:
  - type: web
    name: padel-api
    env: docker
    plan: free
    rootDir: api
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false